### ISSUE TITLE
Fake Credit Card number to test?

### ISSUE THREAD

**Issue by ranouf** [payload-code/payload-code.github.io#4]
Hi,

Do you have some fake credit card number to test the different cases (like processed, refused, ....)?

I searched on google: 
[fake credit card number site:https://docs.payload.co/](https://www.google.com/search?rlz=1C1CHBF_enCA920CA920&ei=zeegX4jiN-bF_QaTsq7wDg&q=fake+credit+card+number+site%3Ahttps%3A%2F%2Fdocs.payload.co%2F&oq=fake+credit+card+number+site%3Ahttps%3A%2F%2Fdocs.payload.co%2F&gs_lcp=CgZwc3ktYWIQA1DWmRBYurcQYMO5EGgAcAB4AIABpwGIAc4QkgEEMjIuM5gBAKABAaoBB2d3cy13aXrAAQE&sclient=psy-ab&ved=0ahUKEwjI_LbIz-XsAhXmYt8KHROZC-4Q4dUDCA0&uact=5)
And on the documentation https://docs.payload.co/ with:
- fake credit card number
- testing credit card number
- card number
- refused card number

But I didn't find it. 

Could you share some?

Thanks

**Comment by bkhattak** [comment]
You can find test card numbers over here : 
https://docs.payload.co/#handle-declines

**Comment by ranouf** [comment]
Thanks
